-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.product
(
    id serial NOT NULL,
    category_id serial NOT NULL,
    name character varying(150) NOT NULL,
    description character varying(300),
	price numeric(10, 2) NOT NULL,
	qty_in_stock integer NOT NULL,
    image character varying(150),
    CONSTRAINT product_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.category
(
    id serial NOT NULL,
    parent_category_id serial,
    name character varying(60) NOT NULL,
    CONSTRAINT category_id PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.site_user
(
    id serial NOT NULL,
    email character varying(100) NOT NULL,
    phone character varying(15) NOT NULL,
    password character varying(50) NOT NULL,
    first_name character varying(60) NOT NULL,
    last_name character varying(60) NOT NULL,
    CONSTRAINT user_pk PRIMARY KEY (id),
    CONSTRAINT email_u UNIQUE (email),
    CONSTRAINT password_u UNIQUE (password),
    CONSTRAINT phone_u UNIQUE (phone)
);

CREATE TABLE IF NOT EXISTS public.address
(
    id serial NOT NULL,
    unit_number character varying(20) NOT NULL,
    street_number character varying(20) NOT NULL,
    address_line_1 character varying(200) NOT NULL,
    address_line_2 character varying(200),
    region character varying(50) NOT NULL,
    country_id serial NOT NULL,
    city character varying(30) NOT NULL,
    postal_code character varying(10) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_address
(
    user_id serial NOT NULL,
    address_id serial NOT NULL,
    "default" boolean NOT NULL
);

CREATE TABLE IF NOT EXISTS public.user_cart
(
    id serial NOT NULL,
    user_id serial NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT user_u UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.cart_item
(
    id serial NOT NULL,
    cart_id serial NOT NULL,
    item_id serial NOT NULL,
    qty serial NOT NULL,
    CONSTRAINT cart_item_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.shop_order
(
    id serial NOT NULL,
    user_id serial NOT NULL,
    order_date date NOT NULL,
    shipping_address_id serial,
    shipping_method_id serial NOT NULL,
    order_status_id serial NOT NULL,
	order_total numeric(10, 2) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.shipping_method
(
    id serial NOT NULL,
    name character varying(30) NOT NULL,
	price numeric(10, 2) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.order_status
(
    id serial NOT NULL,
    status character varying(20) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.order_item
(
    id serial NOT NULL,
    product_item_id serial NOT NULL,
    qty serial NOT NULL,
    order_id serial NOT NULL,
    CONSTRAINT order_item_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_review
(
    id serial NOT NULL,
    ordered_item_id serial NOT NULL,
    user_id serial NOT NULL,
	rating numeric(2, 1) NOT NULL,
    comment character varying(250),
    CONSTRAINT review_pk PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.product
    ADD CONSTRAINT category_fk FOREIGN KEY (category_id)
    REFERENCES public.category (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.category
    ADD CONSTRAINT parent_category_fk FOREIGN KEY (parent_category_id)
    REFERENCES public.category (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.user_address
    ADD CONSTRAINT address_fk FOREIGN KEY (address_id)
    REFERENCES public.address (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.user_address
    ADD CONSTRAINT user_fk FOREIGN KEY (user_id)
    REFERENCES public.site_user (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL
    NOT VALID;


ALTER TABLE IF EXISTS public.user_cart
    ADD CONSTRAINT user_fk FOREIGN KEY (user_id)
    REFERENCES public.site_user (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.cart_item
    ADD CONSTRAINT cart_id_fk FOREIGN KEY (cart_id)
    REFERENCES public.user_cart (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.cart_item
    ADD CONSTRAINT item_id_fk FOREIGN KEY (item_id)
    REFERENCES public.product (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.shop_order
    ADD CONSTRAINT address_fk FOREIGN KEY (shipping_address_id)
    REFERENCES public.address (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.shop_order
    ADD CONSTRAINT shipping_method_fk FOREIGN KEY (shipping_method_id)
    REFERENCES public.shipping_method (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.shop_order
    ADD CONSTRAINT status_fk FOREIGN KEY (order_status_id)
    REFERENCES public.order_status (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.shop_order
    ADD CONSTRAINT user_fk FOREIGN KEY (user_id)
    REFERENCES public.site_user (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.order_item
    ADD CONSTRAINT shop_order_fk FOREIGN KEY (order_id)
    REFERENCES public.shop_order (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.order_item
    ADD CONSTRAINT product_item_id FOREIGN KEY (product_item_id)
    REFERENCES public.product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.user_review
    ADD CONSTRAINT user_fk FOREIGN KEY (user_id)
    REFERENCES public.site_user (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.user_review
    ADD CONSTRAINT ordered_item_fk FOREIGN KEY (ordered_item_id)
    REFERENCES public.order_item (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;

END;